name: Unit Testing & Sonar

on:
  workflow_dispatch:
  pull_request:
    paths: ['contracts/**', 'scripts/**', 'test/**', '.github/workflows/**', 'hardhat.config.ts', 'package.json', 'tsconfig.json', 'sonar-project.properties']
    branches:
      - main
  push:
    paths: ['contracts/**', 'scripts/**', 'test/**', '.github/workflows/**', 'hardhat.config.ts', 'package.json', 'tsconfig.json', 'sonar-project.properties']
    branches:
      - main

jobs:
  run-tests-and-scan:
    name: Runs tests and upload coverage report to Sonar and quality gate check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          docker-compose up -d
          npm install

      - name: Unit tests and coverage
        run: npx hardhat test --network vechain

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
